swagger: '2.0'
info:
  description: |
    Panther Description
  version: 1.0.0
  title: Panther
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: OverrepresentationTest
  description: A
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
# schemes:
# - http
paths:
  /OverrepresentationTest:
    get:
      tags:
      - OverrepresentationTest
      summary: Returns OverrepresentationTest
      description: Returns a map of status codes to quantities
      operationId: getOverrepresentationTest
      produces:
      - application/json
      parameters:
        - name: ontology
          in: query
          description: Annotation Data Set
          required: true
          type: string
          enum: ['GO:0003674', 'GO:0008150', 'GO:0005575']
        - name: species
          in: query
          description: List of reference genes to be used for the analysis
          required: true
          type: string
        - name: test_type
          in: query
          description: List of reference genes to be used for the analysis
          required: true
          type: string
        - name: correction
          in: query
          description: the list of reference genes to be used for the analysis
          required: true
          type: string
        - name: input_type
          in: query
          description: Variant Cell Format.  Currently we support VCF version 4.0 formatthe list of reference genes to be used for the analysis
          required: true
          type: string
        - name: flanking_region
          in: query
          description: Max offset range for SNP position to gene position.  This is used for VCF files.
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
            additionalProperties:
              type: integer
              format: int32
          examples:
            application/json: |-
              {
                reference: {
                  mapped_count: 21042,
                  unmapped_count: 0
                }, 
                input_list: {
                  mapped_count: 2,
                  mapped_id: [
                    MSH2
                    MSH3 ],
                  unmapped_count: 1,
                  unmapped_id: fake
                },
                result: [
                  {
                    number_in_list: 0,
                    expected: 0.3384659252922726,
                    number_in_reference: 3561,
                    pValue: 0,
                    term: {
                      label: UNCLASSIFIED
                    },
                    plus_minus: '-'
                  }, {
                    number_in_list: 2,
                    expected: 0.000380191996958464,
                    number_in_reference: 4,
                    pValue: 0.00031258062671710987,
                    term: {
                      id: 'GO:0043570',
                      label: maintenance of DNA repeat elements,
                    }
                    plus_minus: +
                  }, {
                    number_in_list: 2,
                    expected: 0.0005702879954376961,
                    number_in_reference: 6,
                    pValue: 0.0007033064101134962,
                    term: {
                      id: 'GO:0051096',
                      label: positive regulation of helicase activity,
                    },
                    plus_minus: +
                ]
              }
      security:
      - api_key: []
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /usc/temp/1.0.0
schemes:
 - https
 - http
# Added by API Auto Mocking Plugin
basePath: /panther/temp/1.0.0