swagger: "2.0"
info:
  version: "0.0.1"
  title: Panther API
host: localhost:10011
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /config:
    x-swagger-router-controller: config/config
    get:
      tags:
      - config
      summary: Returns configuration data
      description: Returns a list of supported input data
      operationId: getConfig
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/ConfigResponse"
  /enrichment/overrep:
    x-swagger-router-controller: enrichment/overrep
    get:
      tags:
      - overrep
      summary: Returns Overrepresentation Test
      description: Returns a map of status codes to quantities
      operationId: getOverrep
      produces:
      - application/json
      parameters:
        - name: input
          in: query
          description: List of reference genes to be used for the analysis
          required: true
          type: string
        - name: ontology
          in: query
          description: Annotation Data Set
          required: true
          type: string
          enum: ['GO:0003674', 'GO:0008150', 'GO:0005575']
        - name: species
          in: query
          description: List of species
          required: true
          type: string
        - name: test_type
          in: query
          description: Test types
          required: true
          type: string
        - name: correction
          in: query
          description: Correction
          required: true
          type: string
        - name: input_type
          in: query
          description: Variant Cell Format.  Currently we support VCF version 4.0 formatthe list of reference genes to be used for the analysis
          required: true
          type: string
        - name: flanking_region
          in: query
          description: Max offset range for SNP position to gene position.  This is used for VCF files.
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/OverrepResponse"
definitions:
  ConfigResponse:
    type: object
    required:
      - supported_input
    properties:
      supported_input: 
        type: object
        properties:
          ontology: 
            type: object
          test_type: 
            type: object
  OverrepResponse:
    type: object
    required:
      - results
    properties:
      results:
        type: array
        items:
          type: object
          properties:
            reference: 
              type: object
              properties:
                mapped_count: 
                  type: integer
                unmapped_count: 
                  type: integer
            input_list: 
              type: object
              properties:
                mapped_count:
                  type: integer
                mapped_id:
                  type: array
                  items:
                    type: integer
                unmapped_count:
                  type: integer
                unmapped_id:
                  type: string
            result: 
              type: array
              items:
                properties:
                  number_in_list: 
                    type: integer
                  expected: 
                    type: integer
                  number_in_reference: 
                    type: integer
                  pValue: 
                    type: integer
                  term: 
                    type: object
                    properties:
                      id:
                        type: integer
                      label: 
                        type: string
                  plus_minus: 
                    type: string
            